"""
Resume Q&A Agent - Core logic for processing and querying resumes
"""
import os
import pickle
import re
import numpy as np
from typing import List, Dict, Optional
from sentence_transformers import SentenceTransformer
import faiss
from pypdf import PdfReader
from groq import Groq


class ResumeAgent:
    def __init__(self, model_name: str = "all-MiniLM-L6-v2", groq_model: str = "llama-3.1-8b-instant"):
        """
        Initialize the Resume Agent with a sentence transformer model and Groq LLM.
        
        Args:
            model_name: Hugging Face model name for embeddings
            groq_model: Groq model name for answer generation (default: llama-3.1-8b-instant)
        """
        self.model = SentenceTransformer(model_name)
        self.index = None
        self.texts = []
        self.embeddings = None
        
        # Initialize Groq client
        groq_api_key = os.getenv("GROQ_API_KEY")
        if not groq_api_key:
            raise ValueError("GROQ_API_KEY environment variable is not set. Please set it with your Groq API key.")
        self.groq_client = Groq(api_key=groq_api_key)
        self.groq_model = groq_model
        
    def extract_text_from_pdf(self, pdf_path: str) -> str:
        """Extract text from a PDF file."""
        try:
            reader = PdfReader(pdf_path)
            text = ""
            for page in reader.pages:
                text += page.extract_text() + "\n"
            return text.strip()
        except Exception as e:
            raise Exception(f"Error reading PDF: {str(e)}")
    
    def chunk_text(self, text: str, chunk_size: int = 500, overlap: int = 50) -> List[str]:
        """
        Split text into overlapping chunks for better context.
        
        Args:
            text: Input text
            chunk_size: Size of each chunk in characters
            overlap: Number of characters to overlap between chunks
        """
        if len(text) <= chunk_size:
            return [text]
        
        chunks = []
        start = 0
        while start < len(text):
            end = start + chunk_size
            chunk = text[start:end]
            chunks.append(chunk)
            start = end - overlap
        return chunks
    
    def process_resume(self, pdf_path: str) -> Dict:
        """
        Process a resume PDF and create embeddings.
        
        Args:
            pdf_path: Path to the PDF file
            
        Returns:
            Dictionary with processed data
        """
        # Extract text
        text = self.extract_text_from_pdf(pdf_path)
        
        # Chunk the text
        chunks = self.chunk_text(text)
        self.texts = chunks
        
        # Create embeddings
        print(f"Creating embeddings for {len(chunks)} chunks...")
        self.embeddings = self.model.encode(chunks, show_progress_bar=True)
        
        # Create FAISS index
        dimension = self.embeddings.shape[1]
        self.index = faiss.IndexFlatL2(dimension)
        self.index.add(self.embeddings.astype('float32'))
        
        return {
            "chunks": len(chunks),
            "text_length": len(text)
        }
    
    def search(self, query: str, top_k: int = 3) -> List[Dict]:
        """
        Search for relevant text chunks based on query.
        
        Args:
            query: User's question
            top_k: Number of top results to return
            
        Returns:
            List of relevant text chunks with scores
        """
        if self.index is None or len(self.texts) == 0:
            return []
        
        # Encode query
        query_embedding = self.model.encode([query])
        
        # Search
        distances, indices = self.index.search(query_embedding.astype('float32'), top_k)
        
        results = []
        for i, idx in enumerate(indices[0]):
            if idx < len(self.texts):
                results.append({
                    "text": self.texts[idx],
                    "score": float(distances[0][i]),
                    "rank": i + 1
                })
        
        return results
    
    def answer_question(self, question: str, context_chunks: int = 5) -> str:
        """
        Answer a question about the resume using retrieved context and Groq LLM.
        
        Args:
            question: User's question
            context_chunks: Number of context chunks to use for context
            
        Returns:
            Answer string generated by LLM
        """
        # Search for relevant context
        results = self.search(question, top_k=context_chunks)
        
        if not results:
            return "I couldn't find relevant information in the resume. Please try rephrasing your question."
        
        # Build context from top results (remove duplicates)
        seen_texts = set()
        unique_contexts = []
        for r in results:
            text = r["text"].strip()
            if text and text not in seen_texts:
                seen_texts.add(text)
                unique_contexts.append(text)
        
        if not unique_contexts:
            return "I couldn't find relevant information in the resume. Please try rephrasing your question."
        
        # Combine context chunks
        context = "\n\n".join(unique_contexts)
        
        # Clean up the context (remove excessive whitespace)
        context = re.sub(r'\s+', ' ', context).strip()
        
        # Prepare prompt for LLM
        system_prompt = """You are a helpful assistant that answers questions about a resume. 
Use only the information provided in the context from the resume. 
If the context doesn't contain enough information to answer the question, say so politely.
Be concise, accurate, and professional in your responses."""
        
        user_prompt = f"""Context from the resume:
{context}

Question: {question}

Please provide a clear and accurate answer based on the context above."""
        
        try:
            # Generate answer using Groq LLM
            response = self.groq_client.chat.completions.create(
                model=self.groq_model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.3,  # Lower temperature for more factual responses
                max_tokens=500
            )
            
            answer = response.choices[0].message.content.strip()
            return answer
            
        except Exception as e:
            # Log the error for debugging
            error_msg = str(e)
            print(f"Groq API Error: {error_msg}")
            print(f"Error type: {type(e).__name__}")
            
            # Provide more helpful error message
            if "401" in error_msg or "authentication" in error_msg.lower() or "unauthorized" in error_msg.lower():
                return f"Authentication error with Groq API. Please check your API key. Error: {error_msg}"
            elif "429" in error_msg or "rate limit" in error_msg.lower():
                return f"Rate limit exceeded. Please try again later. Error: {error_msg}"
            elif "model" in error_msg.lower():
                return f"Model error. The model '{self.groq_model}' may not be available. Error: {error_msg}"
            else:
                # Fallback to simple context return if LLM fails
                return f"I encountered an error while generating an answer: {error_msg}\n\nHere's the relevant information from the resume:\n\n{context[:500]}..."
    
    def save(self, filepath: str):
        """Save the agent state to disk."""
        data = {
            "texts": self.texts,
            "embeddings": self.embeddings,
            "index": self.index
        }
        with open(filepath, 'wb') as f:
            pickle.dump(data, f)
    
    def load(self, filepath: str):
        """Load the agent state from disk."""
        with open(filepath, 'rb') as f:
            data = pickle.load(f)
        self.texts = data["texts"]
        self.embeddings = data["embeddings"]
        self.index = data["index"]
        
        # Re-initialize Groq client if not already initialized
        if not hasattr(self, 'groq_client') or self.groq_client is None:
            groq_api_key = os.getenv("GROQ_API_KEY")
            if not groq_api_key:
                raise ValueError("GROQ_API_KEY environment variable is not set. Please set it with your Groq API key.")
            self.groq_client = Groq(api_key=groq_api_key)
            if not hasattr(self, 'groq_model'):
                self.groq_model = "llama-3.1-8b-instant"

